### ISSUE TITLE
Conflict with All-in-One Sidebar and Tab Mix Plus

### ISSUE THREAD

**Issue by JRL2800** [tumpio/toolbarpositionchanger#13]
I don't know how to explain the problem in words, but the screenshot and names explain the problem better than I can with words.

Toolbar Position Changer Problem (01) (Disabled) - Default 01 ![toolbar position changer problem 01 disabled - default 01](https://cloud.githubusercontent.com/assets/27228399/24876773/947165c8-1df2-11e7-8f1e-d5b4abee2810.jpg)

Toolbar Position Changer Problem (02) (Disabled) - Default 02 ![toolbar position changer problem 02 disabled - default 02](https://cloud.githubusercontent.com/assets/27228399/24876774/94744432-1df2-11e7-8449-f6387c0240e6.jpg)

Toolbar Position Changer Problem (03) (Enabled) - Before Customize 01 ![toolbar position changer problem 03 enabled - before customize 01](https://cloud.githubusercontent.com/assets/27228399/24876775/947a8662-1df2-11e7-8475-bab657ebfb9b.jpg)

Toolbar Position Changer Problem (04) (Enabled) - After Customize 01 ![toolbar position changer problem 04 enabled - after customize 01](https://cloud.githubusercontent.com/assets/27228399/24876776/9480e548-1df2-11e7-9b34-89488e896808.jpg)

Toolbar Position Changer Problem (05) (Enabled) - Customize View for the Second Time use 01 ![toolbar position changer problem 05 enabled - customize view for the second time use 01](https://cloud.githubusercontent.com/assets/27228399/24876777/94866784-1df2-11e7-97a3-a9cbb3590344.jpg)

Toolbar Position Changer Problem (06) (Enabled) - After the Customize View for the Second Time use 01 ![toolbar position changer problem 06 enabled - after the customize view for the second time use 01](https://cloud.githubusercontent.com/assets/27228399/24876778/948b5ec4-1df2-11e7-886b-7b84f15f4494.jpg)

**Comment by tumpio** [comment]
Hello,
I found a fix for it. I released a new version that is available once Mozilla has reviewed it.

Thanks for reporting.

**Comment by tumpio** [comment]
Oh and uninstall Toolbar Position Changer and install the new (0.2.10) version again. This will reset the settings so that the All-in-One sidebar's toolbars are excluded correctly.

**Comment by JRL2800** [comment]
ok all we need is to wait for Mozilla has reviewed it and see how the update worked.

**Comment by JRL2800** [comment]
that fixed all the problems but the Sidebar Header it still shows up as a toolbar and not where it is supposed to be after exiting and opening firefox again.

**Comment by tumpio** [comment]
argh, forgot one place where the All-in-one toolbars have to be excluded. I'll do quick beta release so you can test it right away.

**Comment by tumpio** [comment]
Fixed it. Can you test it and confirm that everything works now:
https://addons.mozilla.org/addon/toolbar-position-changer/versions/beta

I'll release it after that. I just read about the beta channel option that allows add-on's to be tested without the mozilla's review process..

**Comment by JRL2800** [comment]
it seams the drag and drop toolbars part is not working so i can't say if it worked or not. Do i need to turn on a setting for the beta to work?

Edit: It did dose work but it needs to be disable and then enable every time you exit and enter firefox.

**Comment by tumpio** [comment]
Can you do this:
- uninstall the beta version
- restart Firefox
- Install the beta version.

After this do you have the same problem?

**Comment by JRL2800** [comment]
I did not need to disable and then enable this time around and is working just fine no problems.

**Comment by tumpio** [comment]
Ok great! 👍 

The problem was that the previous version works incorrectly with All-in-One Sidebar and only way is to uninstall to reset the settings.

**Comment by JRL2800** [comment]
i just found a new problem but this time it is with the Tab Mix Plus it seams it dose not like the muiti-tab.

This is supposed to be two or more rows of tabs.
![toolbar position changer problem with tab mix plus](https://cloud.githubusercontent.com/assets/27228399/24967268/28939cda-1f6f-11e7-8694-1b8be271fcc0.jpg)

**Comment by tumpio** [comment]
Ah I see, I haven't used Tab Mix Plus myself. I'll try to fix this bit later :)

**Comment by tumpio** [comment]
Can you tell me when this happens for you? For me it seems to be working. I'll try to test it more..

**Comment by JRL2800** [comment]
it happened when the tab-bar went from one row to two rows

**Comment by tumpio** [comment]
hmm it has something to do with the Tab bar being below the navigation toolbar.

**Comment by JRL2800** [comment]
yes it is on the bottom.

**Comment by JRL2800** [comment]
It seams when entered firefox with more tabs open than is able to fit in one row I'm able to fix it but not when it goes from one to two rows in the same session it seems.

**Comment by tumpio** [comment]
For me it happens only if I change the position of the tab bar in customize mode. Is this also for you?

If I change the position of the tab bar and then restart firefox (or open a new window), the multirow of tabs works correctly. 

I've found thus far that the element binding for Tab Mix Plus brakes when the tab bar is moved with DOM appendChild. This results that the top attribute of the "old" element is 0, which Tab Mix Plus uses to calculate the number of rows.

I have to contact the author of the Tab Mix Plus to discuss what could be done to fix the issue.

**Comment by tumpio** [comment]
https://bitbucket.org/onemen/tabmixplus/issues/56/multirow-tab-bar-incompatibility-issue

**Comment by tumpio** [comment]
The developer of Tab Mix Plus found a fix for it:
https://bitbucket.org/onemen/tabmixplus/issues/56/multirow-tab-bar-incompatibility-issue#comment-35992193

He will probably soon release a development build that includes the fix.

**Comment by tumpio** [comment]
@JRL2800 Test this development version of Tab Mix Plus that includes the fix for the multirow issue:

https://addons.mozilla.org/en-us/firefox/addon/tab-mix-plus/versions/0.5.0.3pre.170421a1

Does it fix it for you?

**Comment by JRL2800** [comment]
yes that did the trick. It works now and I will let you know if a new problem shows up. Thanks

**Comment by tumpio** [comment]
Great! I'll close this issue report now.
